//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace perpus_project2.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class buku
    {
        public int id_buku { get; set; }
        public string ISBN { get; set; }
        public string judul { get; set; }
        public string penulis { get; set; }
        public string penerbit { get; set; }
        public int tahun { get; set; }
        public int stok { get; set; }
    
        public virtual laporan laporan { get; set; }
    }
}
