//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace perpus_project2.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBPerpusEntities1 : DbContext
    {
        public DBPerpusEntities1()
            : base("name=DBPerpusEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<buku> bukus { get; set; }
        public virtual DbSet<laporan> laporans { get; set; }
        public virtual DbSet<lookuprole> lookuproles { get; set; }
        public virtual DbSet<pelanggan> pelanggans { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<sysuserprofile> sysuserprofiles { get; set; }
        public virtual DbSet<sysuserrole> sysuserroles { get; set; }
        public virtual DbSet<sysuser> sysusers { get; set; }
    }
}
