//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace perpus_project2.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysuser
    {
        public int sysuserid { get; set; }
        public string loginname { get; set; }
        public string passwordencryptedtext { get; set; }
        public int rowcreatedsysuserid { get; set; }
        public System.DateTime rowcreateddatetime { get; set; }
        public int rowmodifiedsysuserid { get; set; }
        public System.DateTime rowmodifieddatetime { get; set; }
    
        public virtual sysuserprofile sysuserprofile { get; set; }
        public virtual sysuserrole sysuserrole { get; set; }
    }
}
